# Generated by Django 3.1.7 on 2021-03-22 00:35


from django.db import migrations


def generate_experiences(apps, schema_editor):
    VOICE_CREDITS = 'Voice Credits'
    MUSIC_GAMES = 'Music - Games'
    MUSIC_MISCELLANEOUS = 'Music - Miscellaneous'
    STREAMING_CREDITS = 'Streaming - Credits'
    CHOICES = (
        (VOICE_CREDITS, VOICE_CREDITS),
        (MUSIC_GAMES, MUSIC_GAMES),
        (MUSIC_MISCELLANEOUS, MUSIC_MISCELLANEOUS),
        (STREAMING_CREDITS, STREAMING_CREDITS),
    )
    Experience = apps.get_model('core', 'Experience')
    experiences = {}
    experiences[VOICE_CREDITS] = [
        {
            'credit': 'Love Is Dead – Wanderer, Armor Games',
            'link': 'https://www.youtube.com/watch?v=14jYul8-Q8Q',
            'year': 2018,
            'tba': False,
        },
        {
            'link': 'http://bunkerpunks.com/',
            'credit': 'Bunker Punks – Kassidee, Cleopatra Rex, Ninja Robot Dinosaur',
            'year': 2018,
            'tba': False,
        },
        {
            'link': 'https://timespinnergame.com/',
            'credit': 'Timespinner – Lunais, Lunar Ray Games',
            'year': 2018,
            'tba': False,
        },
        {
            'link': 'https://www.battlechefbrigade.com/',
            'credit': 'Battle Chef Brigade – Kirin, Lily, Trinket Studios',
            'year': 2017,
            'tba': False,
        },
        {
            'link': 'https://www.youtube.com/watch?v=saGQv8QpezQ',
            'credit': 'Tooth and Tail – The Quartermaster, Pocketwatch Games',
            'year': 2017,
            'tba': False,
        },
        {
            'link': 'https://www.youtube.com/watch?v=-L5zjrezGm0',
            'credit': 'Punch Planet – Cid, Sector-K Games',
            'year': 2017,
            'tba': False,
        },
        {
            'link': 'https://www.youtube.com/watch?v=T7ySp90MNlc&t=24s',
            'credit': 'Relic Hunters – Pinkyy, Rogue Snail',
            'year': 2017,
            'tba': False,
        },
        {
            'link': 'https://www.youtube.com/watch?v=O4Y987JqrbI',
            'credit': 'Ragtags (Animation) – Bea, Storyhive',
            'year': 2017,
            'tba': False,
        },
        {
            'link': 'https://www.youtube.com/watch?v=D7uuz0RW_z8',
            'credit': 'Industries of Titan (trailer) – Council Scout, Brace Yourself Games',
            'year': 2017,
            'tba': False,
        },
        {
            'link': 'https://www.darkestdungeon.com/',
            'credit': 'Darkest Dungeon – The Hag, Red Hook Studios',
            'year': 2016,
            'tba': False,
        },
        {
            'link': 'http://www.leagueoflegends.com/',
            'credit': 'Dragon Trainer Tristana – League of Legends, Riot Games',
            'year': 2015,
            'tba': False,
        },
        {
            'link': 'http://www.leagueoflegends.com/',
            'credit': 'Tristana Reworked – League of Legends, Riot Games',
            'year': 2015,
            'tba': False,
        },
        {
            'link': 'http://www.deadislandepidemic.com/',
            'credit': 'Xian Mei – Dead Island: Epidemic, Deep Silver',
            'year': 2015,
            'tba': False,
        },
        {
            'link': 'http://jointhe509th.com/',
            'credit': 'Engineer – Habitat: A Thousand Generations in Orbit, Versus Evil',
            'year': 2015,
            'tba': False,
        },
        {
            'link': 'https://torment.inxile-entertainment.com/',
            'credit': 'Matkina – Torment: Tides of Numenera, inXile Entertainment',
            'year': 2015,
            'tba': False,
        },
        {
            'link': 'https://www.kickstarter.com/projects/kranggames/emerald',
            'credit': 'Baxter – Emerald, krangGAMES',
            'year': 2015,
            'tba': False,
        },
        {
            'link': 'http://www.dungeonmans.com/',
            'credit': 'Female VO – Dungeonmans, Adventurepro Games',
            'year': 2014,
            'tba': False,
        },
        {
            'link': 'https://www.youtube.com/watch?v=6wL8U_SpKWI',
            'credit': 'Commander – Battle Group 2, Bane Games',
            'year': 2014,
            'tba': False,
        },
        {
            'link': 'http://lionhearttactics.com/',
            'credit': 'Thief/Rogue/Dancer/Assassin – Lionheart Tactics, Emerald City Games',
            'year': 2014,
            'tba': False,
        },
        {
            'link': 'http://www.necrodancer.com/',
            'credit': 'Cadence – Crypt of the NecroDancer, Brace Yourself Games',
            'year': 2014,
            'tba': False,
        },
        {
            'link': '',
            'credit': '(IGF Finalist – Excellence in Audio/Design)',
            'year': None,
            'tba': False,
        },
        {
            'link': 'https://www.youtube.com/watch?v=djHqrqHKOrA',
            'credit': 'Additional Sadira/Orchid vocals – Killer Instinct, Microsoft',
            'year': 2014,
            'tba': False,
        },
        {
            'link': 'https://www.gunsoficarusonline.com/',
            'credit': 'Captain/Gunner/Engineer – Guns of Icarus Online, Muse Games',
            'year': 2014,
            'tba': False,
        },
        {
            'link': 'http://games.disney.com/wheres-my-water-app',
            'credit': 'Allie the Alligator emotes – Where’s My Water, Disney Mobile',
            'year': 2013,
            'tba': False,
        },
        {
            'link': 'https://www.facebook.com/TheTravelerGame',
            'credit': 'Narrator/Ship’s Robot – The Traveler, Game Loop',
            'year': 2013,
            'tba': False,
        },
        {
            'link': 'http://www.newgrounds.com/portal/view/629128',
            'credit': 'Wood Witch – Pact, Lorestrome Productions',
            'year': 2013,
            'tba': False,
        },
        {
            'link': 'http://www.newgrounds.com/portal/view/604440',
            'credit': 'Demon girl – Shadow Tag, Elvidian Productions',
            'year': 2013,
            'tba': False,
        },
    ]
    experiences[MUSIC_GAMES] = [
        {
            'year': 2015,
            'credit': 'krangGAMES – i saw her standing there',
            'tba': False,
            'link': '',
        },
        {
            'year': 2014,
            'credit': ' krangGAMES – i saw her across the world',
            'tba': False,
            'link': 'http://elspetheastman.bandcamp.com/album/i-saw-her-across-the-world-official-soundtrack',
        },
        {
            'year': None,
            'tba': False,
            'credit': '(Canadian Videogame Best Social Game Winner)',
            'link': ''
        },
        {
            'tba': True,
            'credit': 'krangGAMES – Wholesome Family Dinnertime',
            'year': None,
            'link': 'http://www.wholesomefamilydinnertime.com/'
        },
        {
            'tba': True,
            'credit': 'Game Loop – The Traveler',
            'year': None,
            'link': 'https://www.facebook.com/TheTravelerGame'
        },
        {
            'year': 2013,
            'credit': 'Adventure Works – Huck Finn’s River Run',
            'tba': False,
            'link': 'https://play.google.com/store/apps/details?id=com.adventureworks.huck&hl=en'
        },
        {
            'year': 2012,
            'credit': 'Adventure Works – Trip Harrison: Origins',
            'tba': False,
            'link': 'https://itunes.apple.com/us/app/trip-harrison-origins-hd/id448008869?mt=8'
        },
        {
            'year': 2012,
            'credit': 'Adventure Works – Treasure Island Shootout',
            'tba': False,
            'link': 'https://www.facebook.com/AdventureWorksStudios?fref=ts'
        },
    ]
    experiences[MUSIC_MISCELLANEOUS] = [
        {
            'year': 2014,
            'tba': False,
            'credit': 'album – i saw her across the world',
            'link': 'http://elspetheastman.bandcamp.com/album/i-saw-her-across-the-world-official-soundtrack'
        },
        {
            'year': 2013,
            'tba': False,
            'credit': 'album – Return of the Elspeth!',
            'link': 'http://elspetheastman.bandcamp.com/album/return-of-the-elspeth',
        },
        {
            'year': 2012,
            'tba': False,
            'credit': 'album – Elspeth! The Musical',
            'link': 'http://elspetheastman.bandcamp.com/album/elspeth-the-musical',
        },
        {
            'year': None,
            'tba': False,
            'credit': 'Sleepy Ninja Toast – Powerpuff Girls Main Theme remix',
            'link': 'https://www.youtube.com/watch?v=Mci0yv4O5ao',
        },
        {
            'year': None,
            'tba': False,
            'credit': 'Podcast intro – I Do Geek',
            'link': 'http://www.idogeek.com/',
        },
        {
            'year': None,
            'tba': False,
            'credit': 'Sleepy Ninja Toast – Halloween Costumes',
            'link': 'https://www.youtube.com/watch?v=mOmXs6ct814',
        },
        {
            'year': None,
            'tba': False,
            'credit': 'Intro, Background themes – Rated E With Elspeth',
            'link': 'https://www.youtube.com/ratedEwithElspeth',
        },
    ]
    experiences[STREAMING_CREDITS] = []

    for choice in CHOICES:
        for experience in experiences[choice[0]]:
            Experience.objects.create(
                credit=experience['credit'],
                link=experience['link'],
                year=experience['year'],
                tba=experience['tba'],
                category=choice[0]
            )


def generate_projects(apps, schema_editor):
    Project = apps.get_model('core', 'Project')
    projects = [
        {
            'title': 'Love Is Dead - Wanderer (2018)',
            'src': '14jYul8-Q8Q'
        },
        {
            'title': 'Tooth and Tail - The Quartermaster (2017)',
            'src': 'saGQv8QpezQ'
        },
        {
            'title': 'Punch Planet - Cid (2017)',
            'src': '-L5zjrezGm0'
        },
        {
            'title': 'Relic Hunters - Pinkyy (2017)',
            'src': 'T7ySp90MNlc'
        },
        {
            'title': 'Ragtags (Animation) - Bea (2017)',
            'src': 'O4Y987JqrbI'
        },
        {
            'title': 'Industries of Titan (trailer) - Council Scout (2017)',
            'src': 'D7uuz0RW_z8'
        },
        {
            'title': 'League of Legends - Voice of Dragon Trainer Tristana',
            'src': 'pVWPUYRhcEY'
        },
        {
            'title': 'Crypt of the NecroDancer',
            'src': 'CENF14Iloxw'
        },
        {
            'title': 'Falconshield - This is war 4',
            'src': 'dLKTkC6TpF4'
        },
        {
            'title': 'All voices of League of Legends',
            'src': 'mVihJi9IEmM'
        },
        {
            'title': 'League of Legends - Official voice of Tristana',
            'src': 'mamnlBEUU0E'
        },
        {
            'title': 'Timespinner',
            'src': 'QAh5aM0vBVY'
        },
    ]
    for project in projects:
        Project.objects.create(
            src=project['src'],
            title=project['title']
        )


def generate_footer_stats(apps, schema_editor):
    FooterStat = apps.get_model('core', 'FooterStat')
    FooterStat.objects.create(
        value='3457 cups',
        label='of coffee',
        percent=75
    )
    FooterStat.objects.create(
        value='4275 clips',
        label='recorded',
        percent=60
    )
    FooterStat.objects.create(
        value='3744 hours',
        label='streaming',
        percent=65
    )
    FooterStat.objects.create(
        value='467 hours',
        label='of bloopers',
        percent=33
    )


def generate_affiliations(apps, schema_editor):
    Affiliations = apps.get_model('core', 'Affiliations')
    Affiliations.objects.create(
        affiliation='Game Audio Network Guild (G.A.N.G.) Professional',
        link='http://www.audiogang.org/members/elspetheastman/profile/'
    )
    Affiliations.objects.create(
        affiliation='(IGDA) Core Member',
        link='http://www.igda.org/member/elspetheastman'
    )
    Affiliations.objects.create(
        affiliation='Independent Game Developers Association',
        link='http://www.igda.org/member/elspetheastman'
    )


def generate_skills(apps, schema_editor):
    Skills = apps.get_model('core', 'Skills')
    Skills.objects.create(
        game_development="""My first digital audio workstation was Cakewalk in 1997! I've also acted as a game composer
         in Double Fine's 2019 Amnesia Fortnight, and as a featured composer/contributor in Aaron Mark's The Complete
          Guide to Game Audio! I was a member of the Game Audio Network Guild from 2011 to 2015, and an alumni of the
           Game Developers Conference in 2011, 2012, and 2016!""",
        streaming="""I'm a partnered streamer for almost seven years on Twitch and a Twitch Ambassador since 2018! My
         channel has over 34 million views, I've worked with brands like Logitech, Coca-Cola, Xfinity, Mountain Dew,
          Intel, Spotify, and more, plus I've raised over $100,000 for charity!""",
        voice_acting="""I've been voice actor since 2012, starting with Cadence in Crypt of the NecroDancer. I was
         among the first round of signed Creative Artists Agency content creators, and I've hosted the "Voice Acting
         From Your Closet" panel at MAGFest 2016, as well as the TwitchCon 2016/2017 Voice Actors panel. I'm also the
         creator and voice of Nickel the Pig on-stream."""
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_experience_link'),
    ]

    operations = [
        migrations.RunPython(generate_experiences),
        migrations.RunPython(generate_footer_stats),
        migrations.RunPython(generate_skills),
        migrations.RunPython(generate_affiliations),
        migrations.RunPython(generate_projects),
    ]
