# Generated by Django 3.1.7 on 2021-10-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211010_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Sent'),
        ),
    ]
