# Generated by Django 3.1.7 on 2021-10-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20211010_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_created',
            field=models.DateTimeField(blank=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='sent',
            field=models.BooleanField(default=False, verbose_name='Email sent'),
        ),
    ]
