# Generated by Django 3.1.7 on 2021-11-04 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20211010_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='uuid',
            field=models.IntegerField(blank=True, null=True, verbose_name='UUID'),
        ),
    ]
